# a very minimal declarative config file
_format_version: '2.1'
_transform: true

services:
  - host: pokemon-service
    name: pokemon-service
    port: 3000
    protocol: http
    routes:
      - name: pokemon-service-routes
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
        path_handling: v1
        paths:
          - /
        strip_path: true
